name: export-yacd-tar
on:
  workflow_dispatch:   # 允许手动触发
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Pull & Save image
        run: |
          docker pull haishanh/yacd:latest
          docker save -o yacd.tar haishanh/yacd:latest
      - name: Upload tar artifact
        uses: actions/upload-artifact@v4
        with:
          name: yacd-tar
          path: yacd.tar
