name: export-metacubex-tar
on:
  workflow_dispatch:   # 允许手动触发
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Pull & Save image
        run: |
          docker pull metacubex/mihomo
          docker save -o metacubex.tar metacubex/mihomo
      - name: Upload tar artifact
        uses: actions/upload-artifact@v4
        with:
          name: metacubex-tar
          path: metacubex.tar
